Add Blog page
cuhacking/main-website pull request #9
Opened 2020-08-04 10:58 UTC by tejash3402

Add the blog page:

- show all the posts from cuHacking's Ghost CMS
- create a card for each post

Add single post page:

- shows the individual post
- format the article

2020-08-04 18:25 UTC, walsquared requested changes
To test your PR, I made a blog post that has (almost) every single blog element ghost provides. You can see the differences yourself if you launch the local version and go to http://localhost:3000/blog/test-post, then in a new tab go to https://admin.cuhacking.com/test-post/.

There are a number of things that I noticed.

## `blog.tsx`
The design for the blog page is on [Figma](https://www.figma.com/file/cFDzXUk2EfXZ0mN1I7W58i/Website?node-id=104%3A149). From the design, the following things are missing:

- The top banner that says "cuHacking Blog" (I'll DM this to you)
- The featured (latest) post
- The "author info" for each post

Also, a blog post with a missing feature image still needs to look clean. I've provided a default feature image to use if no feature image is sent.

## `single-post.tsx`
Many of the issues are in comments below. The ones listed here are ones I could reference in the code.

- The fifth header style `h5` for some reason is blue and centred... this is also true with the original ghost style, which is weird. It should match the other headers.
- The divider component `hr` isn't properly styled
- The Gallery component from ghost warps the images inside... don't worry about this one though I don't think we'll be using it

---

Everything else is really good! I like what you've done with it, I wasn't even able to come close to getting the styles to match this much.

2020-08-04 18:25 UTC, FemmeQueenInSTEM commented on src/pages/single-post.tsx
> +                                            <time className="byline-meta-date">{posts[0].published_at}</time>
Currently, this outputs a date in the format of `2020-08-04T17:28:26.000+00:00`, however it should output a date in the format of `4 AUG 2020`.

2020-08-04 18:25 UTC, FemmeQueenInSTEM commented on src/pages/single-post.tsx
> +                            <img srcSet={posts[0].feature_image + " 300w, " +
If the feature image does not exist, the page should use the default image.

2020-08-04 18:25 UTC, FemmeQueenInSTEM commented on src/pages/single-post.tsx
> +                                        <h4 className="author-name"><a href="/author/ghost/">{posts[0].primary_author.name}</a></h4>
This should link to `/blog/author/<author_slug>`. There needs to be `/blog` in there, and if the author isn't "ghost" then it needs to link to the appropriate page.

This can be done in a later PR when we create an author page, but it's just something to note.

2020-08-04 18:25 UTC, Walsker commented on src/components/blog-card.tsx
> +                    <div className="date-reading-time">
The author's information should also be shown here.

2020-08-04 18:25 UTC, Walsker commented on src/pages/single-post.tsx
> +                                                    <img className="author-profile-image" src="https://static.ghost.org/v3.0.0/images/ghost.png" alt="Ghost" />
This avatar should be the one that belongs to the author, not the default ghost one. Clicking on it should also lead to the author page, `/blog/author/<author_slug>`.

2020-08-04 18:25 UTC, Walsker commented on src/pages/single-post.tsx
> +        fetch("https://admin.cuhacking.com/ghost/api/v3/content/posts/slug/" + slug + "?key=4ff22bcd0f6effc7d2df8ee82b&include=tags,authors")
We should store the API information in a JSON, then import it. It should look like this:
```json
{
  "url": "https://admin.cuhacking.com",
  "key": "22444f78447824223cefc48062"
}
```

2020-08-06 18:55 UTC, Walsker commented
Related to issue #6.

2020-08-24 00:28 UTC, walsquared approved these changes

2020-08-24 00:34 UTC, merged